apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: todo-app-99-build
  namespace: todo-app-99
  labels:
    name: todo-app-99-build
    app: todo-app-99
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: https://github.com/rpailer/todo-app.git
      ref: cloudant
    contextDir: 
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile    # Look for Dockerfile in: gitUri/contextDir/dockerfilePath
  output:
    to:
      kind: ImageStreamTag
      name: todo-app-99:latest