apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: anis-shkembi-dev
data:
  SERVER_URL: "http://127.0.0.1:3000"
  CLOUDANT_URL: "https://7c8b639f-0c57-4490-b927-f3a3d0b592da-bluemix.cloudantnosqldb.appdomain.cloud"
  CLOUDANT_DB_NAME: "cloudant-db"
